In [1]:
import numpy as np

In [3]:
data = np.random.rand(2, 3, 4)

In [5]:
data

array([[[0.86843472, 0.41753253, 0.37900799, 0.5388874 ],
        [0.29232526, 0.34695843, 0.84447158, 0.2044927 ],
        [0.153723  , 0.9407167 , 0.60822087, 0.6987026 ]],

       [[0.70953459, 0.34268929, 0.45198957, 0.51546617],
        [0.79632619, 0.53905645, 0.63847504, 0.28087951],
        [0.39582395, 0.97041984, 0.17172915, 0.00625582]]])

In [9]:
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2, 2, 2))

In [11]:
data

array([[[0.86843472, 0.41753253, 0.37900799, 0.5388874 ],
        [0.29232526, 0.34695843, 0.84447158, 0.2044927 ],
        [0.153723  , 0.9407167 , 0.60822087, 0.6987026 ]],

       [[0.70953459, 0.34268929, 0.45198957, 0.51546617],
        [0.79632619, 0.53905645, 0.63847504, 0.28087951],
        [0.39582395, 0.97041984, 0.17172915, 0.00625582]]])

In [13]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [17]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [19]:
arr =- np.array([[1,2,3,4],[1,2,3,4]])

In [23]:
arr

array([[-1, -2, -3, -4],
       [-1, -2, -3, -4]])

In [25]:
type(arr)

numpy.ndarray

In [27]:
#Read

In [29]:
#Attrtibutes
shape = data.shape
size = data.size
types = data.dtype

In [31]:
shape

(2, 3, 4)

In [33]:
size

24

In [37]:
types

dtype('float64')

In [39]:
data

array([[[0.86843472, 0.41753253, 0.37900799, 0.5388874 ],
        [0.29232526, 0.34695843, 0.84447158, 0.2044927 ],
        [0.153723  , 0.9407167 , 0.60822087, 0.6987026 ]],

       [[0.70953459, 0.34268929, 0.45198957, 0.51546617],
        [0.79632619, 0.53905645, 0.63847504, 0.28087951],
        [0.39582395, 0.97041984, 0.17172915, 0.00625582]]])

In [41]:
# Slicing
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [43]:
arr

array([[0.86843472, 0.41753253, 0.37900799, 0.5388874 ],
       [0.29232526, 0.34695843, 0.84447158, 0.2044927 ],
       [0.153723  , 0.9407167 , 0.60822087, 0.6987026 ]])

In [45]:
slicer

array([[[0.86843472, 0.41753253, 0.37900799, 0.5388874 ],
        [0.29232526, 0.34695843, 0.84447158, 0.2044927 ],
        [0.153723  , 0.9407167 , 0.60822087, 0.6987026 ]],

       [[0.70953459, 0.34268929, 0.45198957, 0.51546617],
        [0.79632619, 0.53905645, 0.63847504, 0.28087951],
        [0.39582395, 0.97041984, 0.17172915, 0.00625582]]])

In [47]:
reverse

array([[0.70953459, 0.34268929, 0.45198957, 0.51546617],
       [0.79632619, 0.53905645, 0.63847504, 0.28087951],
       [0.39582395, 0.97041984, 0.17172915, 0.00625582]])

In [51]:
singleval

0.868434717690912

In [53]:
# Update

In [55]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [57]:
list1

array([0.02311863, 0.67913526, 0.60800919, 0.71184649, 0.53150128,
       0.23722001, 0.54919304, 0.93711915, 0.74323255, 0.17449446])

In [59]:
list2

array([0.45801584, 0.73834057, 0.83047971, 0.614136  , 0.17354964,
       0.15910315, 0.25080522, 0.29156241, 0.0433524 , 0.49748277])

In [73]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [65]:
add

array([0.48113447, 1.41747583, 1.4384889 , 1.3259825 , 0.70505091,
       0.39632316, 0.79999826, 1.22868155, 0.78658495, 0.67197723])

In [67]:
sub

array([-0.43489721, -0.05920531, -0.22247052,  0.09771049,  0.35795164,
        0.07811686,  0.29838782,  0.64555674,  0.69988015, -0.32298831])

In [69]:
div

array([0.0105887 , 0.50143312, 0.5049393 , 0.43717056, 0.09224185,
       0.03774245, 0.13774048, 0.27322872, 0.03222091, 0.08680799])

In [75]:
mult

array([0.0105887 , 0.50143312, 0.5049393 , 0.43717056, 0.09224185,
       0.03774245, 0.13774048, 0.27322872, 0.03222091, 0.08680799])

In [77]:
dot

2.1141140791113955

In [81]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp((2, 3))
mins = np.min(list1)
maxs = np.max(list1)

In [83]:
sqrt

5.0

In [85]:
ab

2

In [87]:
power

128

In [89]:
log

3.2188758248682006

In [91]:
exp

array([ 7.3890561 , 20.08553692])

In [93]:
mins

0.023118627359501542

In [95]:
maxs

0.9371191458812252

In [97]:
data

array([[[0.86843472, 0.41753253, 0.37900799, 0.5388874 ],
        [0.29232526, 0.34695843, 0.84447158, 0.2044927 ],
        [0.153723  , 0.9407167 , 0.60822087, 0.6987026 ]],

       [[0.70953459, 0.34268929, 0.45198957, 0.51546617],
        [0.79632619, 0.53905645, 0.63847504, 0.28087951],
        [0.39582395, 0.97041984, 0.17172915, 0.00625582]]])

In [99]:
data[0][0][0] = 700

In [101]:
data

array([[[7.00000000e+02, 4.17532530e-01, 3.79007990e-01, 5.38887397e-01],
        [2.92325257e-01, 3.46958434e-01, 8.44471583e-01, 2.04492704e-01],
        [1.53722996e-01, 9.40716704e-01, 6.08220870e-01, 6.98702598e-01]],

       [[7.09534592e-01, 3.42689289e-01, 4.51989572e-01, 5.15466172e-01],
        [7.96326189e-01, 5.39056450e-01, 6.38475039e-01, 2.80879510e-01],
        [3.95823948e-01, 9.70419842e-01, 1.71729148e-01, 6.25582016e-03]]])

In [103]:
data.sort()

In [105]:
data

array([[[3.79007990e-01, 4.17532530e-01, 5.38887397e-01, 7.00000000e+02],
        [2.04492704e-01, 2.92325257e-01, 3.46958434e-01, 8.44471583e-01],
        [1.53722996e-01, 6.08220870e-01, 6.98702598e-01, 9.40716704e-01]],

       [[3.42689289e-01, 4.51989572e-01, 5.15466172e-01, 7.09534592e-01],
        [2.80879510e-01, 5.39056450e-01, 6.38475039e-01, 7.96326189e-01],
        [6.25582016e-03, 1.71729148e-01, 3.95823948e-01, 9.70419842e-01]]])

In [107]:
data = data.reshape(2,2,-1)
data.shape

(2, 2, 6)

In [109]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [111]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [113]:
data

array([[[3.79007990e-01, 4.17532530e-01, 5.38887397e-01, 7.00000000e+02,
         2.04492704e-01, 2.92325257e-01],
        [3.46958434e-01, 8.44471583e-01, 1.53722996e-01, 6.08220870e-01,
         6.98702598e-01, 9.40716704e-01]],

       [[3.42689289e-01, 4.51989572e-01, 5.15466172e-01, 7.09534592e-01,
         2.80879510e-01, 5.39056450e-01],
        [6.38475039e-01, 7.96326189e-01, 6.25582016e-03, 1.71729148e-01,
         3.95823948e-01, 9.70419842e-01]]])

In [117]:
np.delete(data, 0 , axis= 1)

array([[[0.34695843, 0.84447158, 0.153723  , 0.60822087, 0.6987026 ,
         0.9407167 ]],

       [[0.63847504, 0.79632619, 0.00625582, 0.17172915, 0.39582395,
         0.97041984]]])

In [119]:
np.save("new array", data)

In [121]:
test = np.load("new array.npy")

In [123]:
test

array([[[3.79007990e-01, 4.17532530e-01, 5.38887397e-01, 7.00000000e+02,
         2.04492704e-01, 2.92325257e-01],
        [3.46958434e-01, 8.44471583e-01, 1.53722996e-01, 6.08220870e-01,
         6.98702598e-01, 9.40716704e-01]],

       [[3.42689289e-01, 4.51989572e-01, 5.15466172e-01, 7.09534592e-01,
         2.80879510e-01, 5.39056450e-01],
        [6.38475039e-01, 7.96326189e-01, 6.25582016e-03, 1.71729148e-01,
         3.95823948e-01, 9.70419842e-01]]])